# Generated by Django 6.0 on 2026-01-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='allowedemail',
            index=models.Index(fields=['email', 'is_active'], name='allowed_email_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='allowedemail',
            index=models.Index(fields=['is_active'], name='allowed_email_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_admin'], name='user_status_idx'),
        ),
    ]
