# Generated by Django 6.0 on 2026-01-05 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la région')),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('week', models.IntegerField(verbose_name='Semaine ISO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.region', verbose_name='Région')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['region', 'year', 'week'], name='bookings_bo_region__1f8e52_idx'), models.Index(fields=['user', 'year'], name='bookings_bo_user_id_1a955c_idx')],
                'constraints': [models.UniqueConstraint(fields=('region', 'year', 'week'), name='unique_region_year_week', violation_error_message='Cette région est déjà réservée pour cette semaine et cette année.')],
            },
        ),
    ]
