# Generated by Django 6.0 on 2026-01-05 10:31

from django.db import migrations


def load_regions(apps, schema_editor):
    """Charge les 14 régions du Sénégal."""
    Region = apps.get_model('bookings', 'Region')
    
    regions = [
        'Dakar',
        'Diourbel',
        'Fatick',
        'Kaffrine',
        'Kaolack',
        'Kédougou',
        'Kolda',
        'Louga',
        'Matam',
        'Saint-Louis',
        'Sédhiou',
        'Tambacounda',
        'Thiès',
        'Ziguinchor',
    ]
    
    for region_name in regions:
        Region.objects.get_or_create(name=region_name)


def reverse_load_regions(apps, schema_editor):
    """Supprime les régions (pour rollback)."""
    Region = apps.get_model('bookings', 'Region')
    
    regions = [
        'Dakar',
        'Diourbel',
        'Fatick',
        'Kaffrine',
        'Kaolack',
        'Kédougou',
        'Kolda',
        'Louga',
        'Matam',
        'Saint-Louis',
        'Sédhiou',
        'Tambacounda',
        'Thiès',
        'Ziguinchor',
    ]
    
    Region.objects.filter(name__in=regions).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_regions, reverse_load_regions),
    ]
