# Generated by Django 6.0 on 2026-01-05 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_load_regions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_region_year_week_idx',
            old_name='bookings_bo_region__1f8e52_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_user_year_idx',
            old_name='bookings_bo_user_id_1a955c_idx',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='booking_user_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['year', 'week'], name='booking_year_week_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='booking_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['name'], name='region_name_idx'),
        ),
    ]
